import { artifacts } from "hardhat";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { join } from "path";

/**
 * Exports the ConfidentialCampaign ABI (and any saved Sepolia address) into the
 * web app at apps/web/lib/contracts so the frontend has typed, in-sync bindings.
 */
async function main() {
  const campaign = await artifacts.readArtifact("ConfidentialCampaign");

  const outDir = join(__dirname, "..", "..", "..", "apps", "web", "lib", "contracts");
  mkdirSync(outDir, { recursive: true });

  const abiFile = join(outDir, "confidential-campaign-abi.ts");
  writeFileSync(
    abiFile,
    `// AUTO-GENERATED by packages/contracts/scripts/export-abi.ts — do not edit by hand.\n` +
      `export const confidentialCampaignAbi = ${JSON.stringify(
        campaign.abi,
        null,
        2,
      )} as const;\n`,
  );
  console.log(`ABI written: ${abiFile}`);

  // If a deployment exists, surface the address as a generated default.
  const sepoliaPath = join(__dirname, "..", "deployments", "sepolia.json");
  if (existsSync(sepoliaPath)) {
    const dep = JSON.parse(readFileSync(sepoliaPath, "utf8"));
    const addrFile = join(outDir, "deployed-address.ts");
    writeFileSync(
      addrFile,
      `// AUTO-GENERATED from packages/contracts/deployments/sepolia.json.\n` +
        `export const DEPLOYED_CLOAKOPS_ADDRESS = "${dep.contracts.ConfidentialCampaign}" as const;\n` +
        `export const DEPLOYED_TOKEN_ADDRESS = "${dep.contracts.MockConfidentialToken}" as const;\n`,
    );
    console.log(`Deployed address written: ${addrFile}`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
