import { artifacts } from "hardhat";
import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";

/**
 * Exports the ConfidentialCampaign + CloakConfidentialToken ABIs into the web
 * app at apps/web/lib/contracts so the frontend has typed, in-sync bindings.
 * (Deployed addresses are configured via NEXT_PUBLIC_* env vars, not generated.)
 */
async function main() {
  const campaign = await artifacts.readArtifact("ConfidentialCampaign");
  const token = await artifacts.readArtifact("CloakConfidentialToken");

  const outDir = join(__dirname, "..", "..", "..", "apps", "web", "lib", "contracts");
  mkdirSync(outDir, { recursive: true });

  const abiFile = join(outDir, "confidential-campaign-abi.ts");
  writeFileSync(
    abiFile,
    `// AUTO-GENERATED by packages/contracts/scripts/export-abi.ts — do not edit by hand.\n` +
      `export const confidentialCampaignAbi = ${JSON.stringify(
        campaign.abi,
        null,
        2,
      )} as const;\n`,
  );
  console.log(`ABI written: ${abiFile}`);

  const tokenAbiFile = join(outDir, "confidential-token-abi.ts");
  writeFileSync(
    tokenAbiFile,
    `// AUTO-GENERATED by packages/contracts/scripts/export-abi.ts — do not edit by hand.\n` +
      `export const confidentialTokenAbi = ${JSON.stringify(
        token.abi,
        null,
        2,
      )} as const;\n`,
  );
  console.log(`Token ABI written: ${tokenAbiFile}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
